--------------------------------------------------------
--  파일이 생성됨 - 월요일-12월-05-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLASS
--------------------------------------------------------

  CREATE TABLE "CLASS" 
   (	"CLASS_CODE" VARCHAR2(20 BYTE), 
	"INSTRUCTOR_CODE" VARCHAR2(20 BYTE), 
	"CLASS_NAME" VARCHAR2(50 BYTE), 
	"CLASS_LEVEL" VARCHAR2(30 BYTE), 
	"CLASS_CATEGORY" VARCHAR2(20 BYTE), 
	"CLASS_PEORIOD" NUMBER(*,0), 
	"CLASS_PRICE" NUMBER(*,0), 
	"DISCOUNT" NUMBER(*,0), 
	"CLASS_NUMBER" NUMBER(*,0), 
	"CLASS_RD" DATE, 
	"CLASS_DETAIL" VARCHAR2(50 BYTE), 
	"SOLD_NUMBER" NUMBER(*,0) DEFAULT 0, 
	"SOLD_AMOUNT" NUMBER(*,0) DEFAULT 0, 
	"GRADE_AVERAGE" FLOAT(126) DEFAULT 0
   ) ;
REM INSERTING into CLASS
SET DEFINE OFF;
Insert into CLASS (CLASS_CODE,INSTRUCTOR_CODE,CLASS_NAME,CLASS_LEVEL,CLASS_CATEGORY,CLASS_PEORIOD,CLASS_PRICE,DISCOUNT,CLASS_NUMBER,CLASS_RD,CLASS_DETAIL,SOLD_NUMBER,SOLD_AMOUNT,GRADE_AVERAGE) values ('cc1612050001','ic1612050001','너는누구야','입문자','단과',30,100000,0,20,to_date('03/06/01','RR/MM/DD'),'나는 누구인가',10,1000000,4);
Insert into CLASS (CLASS_CODE,INSTRUCTOR_CODE,CLASS_NAME,CLASS_LEVEL,CLASS_CATEGORY,CLASS_PEORIOD,CLASS_PRICE,DISCOUNT,CLASS_NUMBER,CLASS_RD,CLASS_DETAIL,SOLD_NUMBER,SOLD_AMOUNT,GRADE_AVERAGE) values ('cc1612050002','ic1612050001','그것은 무엇이야','초급','단과',30,100000,0,20,to_date('03/06/02','RR/MM/DD'),'그것은 무엇인가',15,1500000,4);
Insert into CLASS (CLASS_CODE,INSTRUCTOR_CODE,CLASS_NAME,CLASS_LEVEL,CLASS_CATEGORY,CLASS_PEORIOD,CLASS_PRICE,DISCOUNT,CLASS_NUMBER,CLASS_RD,CLASS_DETAIL,SOLD_NUMBER,SOLD_AMOUNT,GRADE_AVERAGE) values ('cp1612050001','ic1612050001','너와나의 연결고리','중급','패키지',60,200000,10,40,to_date('03/06/03','RR/MM/DD'),'알아보자',13,2340000,4.5);
Insert into CLASS (CLASS_CODE,INSTRUCTOR_CODE,CLASS_NAME,CLASS_LEVEL,CLASS_CATEGORY,CLASS_PEORIOD,CLASS_PRICE,DISCOUNT,CLASS_NUMBER,CLASS_RD,CLASS_DETAIL,SOLD_NUMBER,SOLD_AMOUNT,GRADE_AVERAGE) values ('cp1612050002','ic1612050001','(고급)연결고리','고급','패키지',90,300000,20,60,to_date('03/06/04','RR/MM/DD'),'(고급)알아보자',15,3600000,4.2);
--------------------------------------------------------
--  DDL for Index CLASS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLASS_PK" ON "CLASS" ("CLASS_CODE") 
  ;
--------------------------------------------------------
--  Constraints for Table CLASS
--------------------------------------------------------

  ALTER TABLE "CLASS" ADD CONSTRAINT "CLASS_PK" PRIMARY KEY ("CLASS_CODE") ENABLE;
  ALTER TABLE "CLASS" MODIFY ("CLASS_DETAIL" NOT NULL ENABLE);
  ALTER TABLE "CLASS" MODIFY ("CLASS_RD" NOT NULL ENABLE);
  ALTER TABLE "CLASS" MODIFY ("CLASS_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "CLASS" MODIFY ("DISCOUNT" NOT NULL ENABLE);
  ALTER TABLE "CLASS" MODIFY ("CLASS_PRICE" NOT NULL ENABLE);
  ALTER TABLE "CLASS" MODIFY ("CLASS_PEORIOD" NOT NULL ENABLE);
  ALTER TABLE "CLASS" MODIFY ("CLASS_CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "CLASS" MODIFY ("CLASS_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "CLASS" MODIFY ("CLASS_NAME" NOT NULL ENABLE);
  ALTER TABLE "CLASS" MODIFY ("INSTRUCTOR_CODE" NOT NULL ENABLE);
  ALTER TABLE "CLASS" MODIFY ("CLASS_CODE" NOT NULL ENABLE);
