--------------------------------------------------------
--  파일이 생성됨 - 월요일-12월-05-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLASS_ORDER
--------------------------------------------------------

  CREATE TABLE "CLASS_ORDER" 
   (	"ORDER_CODE" VARCHAR2(20 BYTE), 
	"MEMBER_ID" VARCHAR2(20 BYTE), 
	"CLASS_CODE" VARCHAR2(20 BYTE), 
	"ORDER_NUMBER" VARCHAR2(20 BYTE), 
	"ORDER_DATE" DATE, 
	"ORDER_PRICE" NUMBER(*,0), 
	"DEPOSITOR" VARCHAR2(20 BYTE), 
	"ORDER_STATE" VARCHAR2(20 BYTE), 
	"SERVICE_STATE" VARCHAR2(20 BYTE), 
	"SERVICE_START" DATE, 
	"SERVICE_PERIOD" NUMBER(*,0), 
	"SERVICE_END" DATE, 
	"REVIEW_CHECK" NUMBER(*,0)
   ) ;
REM INSERTING into CLASS_ORDER
SET DEFINE OFF;
Insert into CLASS_ORDER (ORDER_CODE,MEMBER_ID,CLASS_CODE,ORDER_NUMBER,ORDER_DATE,ORDER_PRICE,DEPOSITOR,ORDER_STATE,SERVICE_STATE,SERVICE_START,SERVICE_PERIOD,SERVICE_END,REVIEW_CHECK) values ('oc1612050001','id001','cc1612050001','on1612050001',to_date('16/12/05','RR/MM/DD'),20000,'홍인용','대기중','대기',null,60,null,null);
Insert into CLASS_ORDER (ORDER_CODE,MEMBER_ID,CLASS_CODE,ORDER_NUMBER,ORDER_DATE,ORDER_PRICE,DEPOSITOR,ORDER_STATE,SERVICE_STATE,SERVICE_START,SERVICE_PERIOD,SERVICE_END,REVIEW_CHECK) values ('oc1612050002','id002','cc1612050002','on1612040001',to_date('16/12/04','RR/MM/DD'),10000,'김진남','결재완료','정상',to_date('16/12/04','RR/MM/DD'),30,to_date('17/01/04','RR/MM/DD'),null);
Insert into CLASS_ORDER (ORDER_CODE,MEMBER_ID,CLASS_CODE,ORDER_NUMBER,ORDER_DATE,ORDER_PRICE,DEPOSITOR,ORDER_STATE,SERVICE_STATE,SERVICE_START,SERVICE_PERIOD,SERVICE_END,REVIEW_CHECK) values ('oc1612050003','id003','cc1612010001','on1612050002',to_date('16/12/05','RR/MM/DD'),30000,'방상엽','대기중','대기',null,90,null,null);
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TABLE1_PK" ON "CLASS_ORDER" ("ORDER_CODE") 
  ;
--------------------------------------------------------
--  Constraints for Table CLASS_ORDER
--------------------------------------------------------

  ALTER TABLE "CLASS_ORDER" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ORDER_CODE") ENABLE;
  ALTER TABLE "CLASS_ORDER" MODIFY ("SERVICE_STATE" NOT NULL ENABLE);
  ALTER TABLE "CLASS_ORDER" MODIFY ("ORDER_STATE" NOT NULL ENABLE);
  ALTER TABLE "CLASS_ORDER" MODIFY ("DEPOSITOR" NOT NULL ENABLE);
  ALTER TABLE "CLASS_ORDER" MODIFY ("ORDER_PRICE" NOT NULL ENABLE);
  ALTER TABLE "CLASS_ORDER" MODIFY ("ORDER_DATE" NOT NULL ENABLE);
  ALTER TABLE "CLASS_ORDER" MODIFY ("ORDER_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "CLASS_ORDER" MODIFY ("CLASS_CODE" NOT NULL ENABLE);
  ALTER TABLE "CLASS_ORDER" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "CLASS_ORDER" MODIFY ("ORDER_CODE" NOT NULL ENABLE);
