--------------------------------------------------------
--  파일이 생성됨 - 월요일-12월-05-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "MEMBER" 
   (	"MEMBER_ID" VARCHAR2(20 BYTE), 
	"MEMBER_PW" VARCHAR2(20 BYTE), 
	"MEMBER_NAME" VARCHAR2(20 BYTE), 
	"MEMBER_BIRTH" NUMBER(*,0), 
	"MEMBER_PHONE" VARCHAR2(20 BYTE), 
	"MEMBER_GENDER" CHAR(3 BYTE), 
	"MEMBER_ADDR" VARCHAR2(50 BYTE), 
	"MEMBER_RD" DATE, 
	"MEMBER_LEVEL" VARCHAR2(30 BYTE)
   ) ;
REM INSERTING into MEMBER
SET DEFINE OFF;
Insert into MEMBER (MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_GENDER,MEMBER_ADDR,MEMBER_RD,MEMBER_LEVEL) values ('id001','pw001','홍길동',880701,'01011112222','남','전주시 덕진구',to_date('16/12/05','RR/MM/DD'),'admin');
Insert into MEMBER (MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_GENDER,MEMBER_ADDR,MEMBER_RD,MEMBER_LEVEL) values ('id002','pw001','유관순',880701,'01011112222','남','전주시 덕진구',to_date('16/12/05','RR/MM/DD'),'manager');
Insert into MEMBER (MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_GENDER,MEMBER_ADDR,MEMBER_RD,MEMBER_LEVEL) values ('id003','pw001','황진희',880701,'01011112222','남','전주시 덕진구',to_date('16/12/05','RR/MM/DD'),'member');
Insert into MEMBER (MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_GENDER,MEMBER_ADDR,MEMBER_RD,MEMBER_LEVEL) values ('id004','pw001','변사또',880701,'01011112222','남','전주시 덕진구',to_date('16/12/05','RR/MM/DD'),'member');
Insert into MEMBER (MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_PHONE,MEMBER_GENDER,MEMBER_ADDR,MEMBER_RD,MEMBER_LEVEL) values ('id005','pw001','성춘향',880701,'01011112222','남','전주시 덕진구',to_date('16/12/05','RR/MM/DD'),'member');
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "MEMBER" MODIFY ("MEMBER_RD" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("MEMBER_ADDR" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("MEMBER_GENDER" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("MEMBER_PHONE" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("MEMBER_BIRTH" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("MEMBER_NAME" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("MEMBER_PW" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
